# Generated by Django 3.0.8 on 2020-07-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadenaEvolucion', '0004_auto_20200719_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nivelEvolutivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
